Выполнена задача 2
k4noise/AnkiBot pull request #17
Opened 2024-11-14 17:48 UTC by k4noise

Добавили режимы изучения колод:
- С ввводом терминов
- С оценкой запоминания карточек
- С сопоставлением терминов определению
Также реализовали досрочный выход из обучения.

2024-11-17 12:11 UTC, YaEtoTui commented
Немного ремарок по поводу git. 

1) Могли сразу сделать pull request в master. Так как после выполнения 1 задачи вы вливаете изменения в master. А потом решив конфликты и сделав задачу 2. Могли влить в master, чтобы не делать по несколько раз pull request.
2) Когда делаете задачи. Особенно в разных ветках, было бы понятнее для истории указывать в какой ветке были коммиты.

2024-11-17 12:17 UTC, YaEtoTui commented on src/main/java/ru/rtf/telegramBot/commands/RenameDeckCommandHandler.java
> +    public String handle(DeckManager usersDecks, Long id, String[] params) {
id -> немножко не понятное название, хотелось бы делать поточнее.
Почему вам не понравилось chatId? 
Для меня это как number писать

Я знаю что у вас javaDoc, но бывает на практике, люди не смотрят прямо в код, а читают с репозитория как в github изменения

2024-11-17 12:19 UTC, YaEtoTui commented on src/main/java/ru/rtf/telegramBot/learning/LearningSession.java
> +    String SHOW_RIGHT_ANSWER = """
инкапсуляции нет. Как минимум. Нигде кроме данного класса не используете

2024-11-17 12:28 UTC, YaEtoTui commented on src/main/java/ru/rtf/telegramBot/CommandHandler.java
> +            Ошибка выполнения команды Подробности:
Точку точно не надо было убирать)

2024-11-17 12:36 UTC, YaEtoTui commented on src/test/java/ru/rtf/CardTest.java
> +                IllegalArgumentException.class,
Такс девочки. Вспоминаем лекцию по тестам. 
Как считаете так проверять exception корректно?

Еще чего-то не хватает тут в данной методе

2024-11-17 12:51 UTC, YaEtoTui commented
2 задание принято

2024-11-17 14:55 UTC, k4noise commented on src/test/java/ru/rtf/CardTest.java
> +                IllegalArgumentException.class,
Для истории: не хватает проверки сообщения исключения, мы это исправили в 1 задаче, но пока не сливали во вторую.
![image](https://github.com/user-attachments/assets/bf5482c2-8ac9-4ec2-89ec-5e5373c8d172)

2024-11-24 10:23 UTC, vpyzhyanov requested changes
Вы думали я не замечу отсутствие тестов? Нет тестов на новые команды

```java
        commands.put("/check", new LearnCheckCommandHandler(sessionManager));
        commands.put("/end_check", new EndCheckCommandHandler(sessionManager));
```

Снова зашли на тёмную сторону.

2024-11-24 10:23 UTC, vpyzhyanov commented on src/main/java/ru/rtf/telegramBot/TelegramBotCore.java
> +                    : sessionManager.handle(chatId, message.getText());
Добро пожаловать на тёмную сторону. Теперь обработкой сообщения пользователя занимаются аж 2 класса. Выберите один.

Самое интересное, что CommandManager тоже использует SessionManager

2024-11-24 10:23 UTC, vpyzhyanov commented on src/main/java/ru/rtf/telegramBot/commands/CreateCardCommandHandler.java
> +    public String handle(DeckManager usersDecks, Long id, String[] params) {
Надо было пользоваться встроенным инструментом изменения сигнатуры, тогда такой ситуации бы не возникло.

Что это за id? Как понять? Тут и везде надо писать от какого объекта этот идентификатор. `chatId`

2024-11-24 10:23 UTC, vpyzhyanov commented on src/main/java/ru/rtf/telegramBot/commands/LearnCheckCommandHandler.java
> +    private final int COUNT_PARAMS = 2;
static

2024-11-24 10:23 UTC, vpyzhyanov commented on src/main/java/ru/rtf/telegramBot/commands/LearnCheckCommandHandler.java
> +        } catch (IllegalArgumentException | NoSuchElementException | IllegalStateException exception) {
если хотите поймать все исключения, то можете написать `Exception`

2024-11-24 10:23 UTC, vpyzhyanov commented on src/main/java/ru/rtf/telegramBot/commands/StartCommandHandler.java
> +        return "Добро пожаловать в AnkiBot\\. Введите команду /help, чтобы посмотреть доступные команды";
зачем слеш?

2024-11-24 10:23 UTC, vpyzhyanov commented on src/main/java/ru/rtf/telegramBot/learning/LearningSession.java
> +    String SHOW_RIGHT_ANSWER = """
в интерфейсе private сделать не получится. Интерфейс на то и интерфейс, чтобы в нём всё было публичное

2024-11-24 10:23 UTC, vpyzhyanov commented on src/main/java/ru/rtf/telegramBot/learning/LearningSession.java
> +     * @return Сформулированный вопрос
не надо 2 раза писать одно и то же. Это поле нужно не для этого

2024-11-24 10:23 UTC, vpyzhyanov commented on src/main/java/ru/rtf/telegramBot/learning/LearningSession.java
> +     * @return Правильность ответа
и тут тоже

2024-11-24 10:23 UTC, vpyzhyanov commented on src/main/java/ru/rtf/telegramBot/learning/SessionManager.java
> +    public String handle(Long chatId, String text) {
Перегрузили этот класс функционалом. Он и обрабатывает сообщение от пользователя и управляет сессией. Одно это действие добавило вам и перегруз по функционалу и коллективную безотстветственность, т.к. класс по обработке сообщений уже есть.

2024-11-24 10:23 UTC, vpyzhyanov commented on src/main/java/ru/rtf/telegramBot/learning/SessionManager.java
> +                ? "Вы досрочно завершили сессию"
в нормальной ситуации (когда ответственность распределена правильно) этот класс не должен общаться с пользователями.

2024-11-24 10:23 UTC, vpyzhyanov commented on src/main/java/ru/rtf/telegramBot/learning/SessionManager.java
> +    public LearningSession get(Long chatId) {
не используется. Удаляем

2024-11-24 10:23 UTC, vpyzhyanov commented on src/main/java/ru/rtf/telegramBot/learning/mode/MatchLearning.java
> +        allCards = new LinkedList<>(cards);
почему выбрана именно такая коллекция?

2024-11-24 10:23 UTC, vpyzhyanov commented on src/main/java/ru/rtf/telegramBot/learning/mode/MatchLearning.java
> +        return new Random().nextInt(allDefinitions.size());
`new Random()` надо вынести в поле и не создавать его каждый раз

2024-11-24 10:23 UTC, vpyzhyanov commented on src/main/java/ru/rtf/telegramBot/learning/mode/TypingLearning.java
> +        return allCards.poll().toString();
Дублирование. Вам бы тут абстрактный класс пригодился. Даже коллекция абсолютно одинаковая.

![image](https://github.com/user-attachments/assets/c01254fd-ee79-4279-9ec9-e1c079b58941)

2024-11-24 10:23 UTC, vpyzhyanov commented on src/main/java/ru/rtf/telegramBot/learning/mode/TypingLearning.java
> +    public String pullActiveCardDescription() {
снова тёмная сторона. И удаляет и что-то возвращает

2024-11-24 10:23 UTC, vpyzhyanov commented on src/test/java/ru/rtf/telegramBot/CommandManagerTest.java
> +        Assertions.assertEquals("Ошибка параметров команды\n Проверьте на соответствие шаблону \\(/help\\)", message);
откуда взялся слеш?

2024-11-24 10:23 UTC, vpyzhyanov commented on src/test/java/ru/rtf/telegramBot/learning/SessionManagerTest.java
> +        Assertions.assertEquals("Вы досрочно завершили сессию", endMessage);
очень ненадёжная проверка. Всегда используйте assertEquals

2024-11-24 10:23 UTC, vpyzhyanov commented on src/test/java/ru/rtf/telegramBot/learning/SessionManagerTest.java
> +        Assertions.assertTrue(endMessage.contains("Вы прошли все карточки в колоде!"));
и тут

2024-11-24 10:23 UTC, vpyzhyanov commented on src/test/java/ru/rtf/telegramBot/learning/mode/MatchLearningTest.java
> +                1 - верно, 0 - неверно""", question);
тест закончился на самом интересном месте. Слишком мелко разбили тесты

2024-11-24 10:25 UTC, vpyzhyanov commented
Задачу 2 только Влада делала?

![image](https://github.com/user-attachments/assets/47164926-0816-47c1-94da-edfd89f61997)

2024-11-24 10:42 UTC, k4noise commented
> Задачу 2 только Влада делала?
> 
> ![image](https://private-user-images.githubusercontent.com/71599019/389264799-47164926-0816-47c1-94da-edfd89f61997.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0NDUyMDYsIm5iZiI6MTczMjQ0NDkwNiwicGF0aCI6Ii83MTU5OTAxOS8zODkyNjQ3OTktNDcxNjQ5MjYtMDgxNi00N2MxLTk0ZGEtZWRmZDg5ZjYxOTk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI0VDEwNDE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4ODVhMzRmNjM4NTc3NTQxZjVjMDU3MTcyZTU2YjZmMjk2YzhmNjdiYmJhMjY5MTBiZWE5NmIwZTZiMmM4NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ag8LJHM6L5fTRjwCHSiE1CCblw8PmMRK3hZEZpuB3-U)

за случайное редактирование пожалуйста извините.
я свою ветку удалила в процессе решения проблемы конфликта и забыла вернуть.
ветку на место вернула

2024-11-26 08:43 UTC, k4noise commented on src/test/java/ru/rtf/CardTest.java
> +                IllegalArgumentException.class,
upd Все изменения с первой задачи слиты, заодно и решили конфликт

2024-12-01 16:15 UTC, VladaAlmazova commented on src/main/java/ru/rtf/telegramBot/CommandHandler.java
> +            Ошибка выполнения команды Подробности:
вернули

2024-12-01 16:19 UTC, VladaAlmazova commented on src/main/java/ru/rtf/telegramBot/learning/LearningSession.java
> +    String SHOW_RIGHT_ANSWER = """
сделали вместо интерфейса абстрактный класс и добавили private

2024-12-01 16:20 UTC, VladaAlmazova commented on src/main/java/ru/rtf/telegramBot/commands/CreateCardCommandHandler.java
> +    public String handle(DeckManager usersDecks, Long id, String[] params) {
исправили на chatId

2024-12-01 16:20 UTC, VladaAlmazova commented on src/main/java/ru/rtf/telegramBot/commands/LearnCheckCommandHandler.java
> +    private final int COUNT_PARAMS = 2;
Добавила

2024-12-01 16:21 UTC, VladaAlmazova commented on src/main/java/ru/rtf/telegramBot/commands/LearnCheckCommandHandler.java
> +        } catch (IllegalArgumentException | NoSuchElementException | IllegalStateException exception) {
сократила до `Exception`

2024-12-01 16:22 UTC, VladaAlmazova commented on src/main/java/ru/rtf/telegramBot/commands/StartCommandHandler.java
> +        return "Добро пожаловать в AnkiBot\\. Введите команду /help, чтобы посмотреть доступные команды";
забыла убрать после неудачной попытки внедрить форматирование

2024-12-01 16:22 UTC, VladaAlmazova commented on src/main/java/ru/rtf/telegramBot/commands/StartCommandHandler.java
> +        return "Добро пожаловать в AnkiBot\\. Введите команду /help, чтобы посмотреть доступные команды";
убрала

2024-12-01 16:23 UTC, VladaAlmazova commented on src/main/java/ru/rtf/telegramBot/learning/LearningSession.java
> +     * @return Сформулированный вопрос
убрали дублирование

2024-12-01 16:23 UTC, VladaAlmazova commented on src/main/java/ru/rtf/telegramBot/learning/LearningSession.java
> +     * @return Правильность ответа
убрали

2024-12-01 16:23 UTC, VladaAlmazova commented on src/main/java/ru/rtf/telegramBot/learning/SessionManager.java
> +    public LearningSession get(Long chatId) {
удалили

2024-12-01 16:23 UTC, VladaAlmazova commented on src/main/java/ru/rtf/telegramBot/learning/mode/MatchLearning.java
> +        return new Random().nextInt(allDefinitions.size());
вынесли в поле

2024-12-01 16:25 UTC, VladaAlmazova commented on src/main/java/ru/rtf/telegramBot/learning/mode/TypingLearning.java
> +        return allCards.poll().toString();
изменила интерфейс на абстрактный класс

2024-12-01 16:25 UTC, VladaAlmazova commented on src/main/java/ru/rtf/telegramBot/learning/mode/TypingLearning.java
> +    public String pullActiveCardDescription() {
разделили на два метода

2024-12-01 16:26 UTC, VladaAlmazova commented on src/test/java/ru/rtf/telegramBot/CommandManagerTest.java
> +        Assertions.assertEquals("Ошибка параметров команды\n Проверьте на соответствие шаблону \\(/help\\)", message);
убрала, случайно остался после попытки внедрить форматирование

2024-12-01 16:33 UTC, VladaAlmazova commented on src/test/java/ru/rtf/telegramBot/learning/SessionManagerTest.java
> +        Assertions.assertEquals("Вы досрочно завершили сессию", endMessage);
заменила `assertFalse` на `assertEquals`, если вы это имели в виду

2024-12-01 16:34 UTC, VladaAlmazova commented on src/test/java/ru/rtf/telegramBot/learning/SessionManagerTest.java
> +        Assertions.assertTrue(endMessage.contains("Вы прошли все карточки в колоде!"));
написала полный текст сообщения вместо `contains`

2024-12-01 16:35 UTC, VladaAlmazova commented on src/test/java/ru/rtf/telegramBot/learning/mode/MatchLearningTest.java
> +                1 - верно, 0 - неверно""", question);
объединила тесты

2024-12-01 18:09 UTC, k4noise commented on src/main/java/ru/rtf/telegramBot/learning/mode/MatchLearning.java
> +        allCards = new LinkedList<>(cards);
Изначальный выбор был между коллекциями из `List` или `Queue`.

От коллекции мы хотели константный доступ к __активной__ (изучаемой на данный момент) карте с наименьшим количеством операций для этого. Коллекции из `List` отпали, поскольку обеспечить быстрый доступ к активной карте без доп. операций (отслеживание индекса и его граничных случаев) мы не можем. Для того, чтобы не усложнять код, была выбрана реализация с использованием коллекций из `Queue`.

Дальше, выбирая подходящую коллекцию из очередей, я допустила ошибку - рассуждая ранее про коллекции `List`, не задумываясь выбрала `LinkedList`. Очередь же? Очередь, но не самая оптимальная по памяти для нас. Потребности в удалении текущего элемента во время итерации (преимущество `LinkedList`) у нас нет, поэтому реализация на связном списке избыточна. Вместо нее выбрала реализацию на динамических массивах, более эффективную для вставки/удаления в лице `ArrayDeque`. (Взято [отсюда](https://docs.oracle.com/javase/tutorial/collections/implementations/deque.html))

Коллекция изменена на `ArrayDeque`.

2024-12-01 18:10 UTC, k4noise commented on src/main/java/ru/rtf/telegramBot/TelegramBotCore.java
> +                    : sessionManager.handle(chatId, message.getText());
Исправлено, теперь обработкой занимается один класс - `MessageHandler`

2024-12-01 18:12 UTC, k4noise commented on src/main/java/ru/rtf/telegramBot/learning/SessionManager.java
> +    public String handle(Long chatId, String text) {
Теперь `handle` обрабатывается в `MessageHandler`, остальное общение с пользователем перенесено в обработчики команд, а этот класс __только__ управляет сессиями.

2024-12-01 18:13 UTC, k4noise commented on src/main/java/ru/rtf/telegramBot/learning/SessionManager.java
> +                ? "Вы досрочно завершили сессию"
Уже не общается, именно это место перенесено в `EndCheckCommandHandler`

2024-12-01 18:18 UTC, k4noise commented on src/main/java/ru/rtf/telegramBot/learning/SessionManager.java
> +    public LearningSession get(Long chatId) {
Теперь используется, вернула на место.
При разделении ответственности этого класса реализация без этого метода у меня не получилась

2024-12-05 18:29 UTC, vpyzhyanov commented on src/main/java/ru/rtf/telegramBot/learning/LearningSession.java
> +    String SHOW_RIGHT_ANSWER = """
Не самое лучшее решение. Боролись за инкапсуляцию, но проблема была глубже, проблема в тёмной стороне "коллективная безотстветственость".  Давайте разбираться

1. Цель констант - участие в формировании сообщения **пользователю** о том правильный ли у него ответ.
2. Цель LearningSession можно легко увидеть по его интерфейсным/абстрактным методам:
![image](https://github.com/user-attachments/assets/8a8718bb-134b-4fef-87df-65f293134f37)

И где тут ответ пользователю? Правильно, нигде, ведь его тут и быть не должно.

Правильный путь был в том, чтобы посмотреть где эти константы реально нужны, а нужны они в одном единственном месте класса `MessageHandler`. Вот туда их и надо было перенести. И уже не только одна из них private, а **ВСЕ**. Так и инкапсуляция будет и будете на светлой стороне

2024-12-05 19:49 UTC, vpyzhyanov approved these changes
Жалко, что тёмная сторона ещё осталась. Как исправите, можете мёрджить, задача принята.

2024-12-05 19:49 UTC, vpyzhyanov commented on src/main/java/ru/rtf/telegramBot/learning/LearningSession.java
> +    public static final String INCORRECT_ANSWER_INFO = "Неверно. " + SHOW_RIGHT_ANSWER;
как я говорил выше, убираем все эти поля отсюда

2024-12-05 19:49 UTC, vpyzhyanov commented on src/main/java/ru/rtf/telegramBot/learning/LearningSession.java
> +        return allCards.peek().toString();
1. Я на прошлом занятии рассказывал, что использовать toString() для бизнес-логики ни в коем случае нельзя! Убираем
2. Не обработан возможный NPE
3. Логическая ошибка: У карты не существует описания. Я бы ожидал что-то вроде getActiveCard().getDescription().

С одной стороны класс инкапсулирует карточку, а с другой стороны эти карточки пришли снаружи, и если мы должны уметь получать их описание, то почему бы не получить карточку целиком `getActiveCard()`

2024-12-05 19:49 UTC, vpyzhyanov commented on src/test/java/ru/rtf/telegramBot/learning/SessionManagerTest.java
> +        Assertions.assertEquals("Вы досрочно завершили сессию", endMessage);
Похоже не на ту строчку написал замечание. Оно было написано на 

`Assertions.assertTrue(endMessage.contains("Вы прошли все карточки в колоде!"));`

2024-12-05 19:54 UTC, vpyzhyanov commented
Оценка

- Git: 3 б
- ООП: 4 б (снизил 1 балл за коллективную безответственность и использование toString() для логики)

2024-12-09 11:28 UTC, VladaAlmazova commented on src/main/java/ru/rtf/telegramBot/learning/LearningSession.java
> +    String SHOW_RIGHT_ANSWER = """
убрали текстовые константы в `MessageHandler`

2024-12-09 11:28 UTC, VladaAlmazova commented on src/test/java/ru/rtf/telegramBot/learning/SessionManagerTest.java
> +        Assertions.assertEquals("Вы досрочно завершили сессию", endMessage);
написала полный текст сообщения вместо contains

2024-12-09 11:31 UTC, VladaAlmazova commented on src/main/java/ru/rtf/telegramBot/learning/LearningSession.java
> +    public static final String INCORRECT_ANSWER_INFO = "Неверно. " + SHOW_RIGHT_ANSWER;
убрали в `MessageHandler`

2024-12-09 11:34 UTC, VladaAlmazova commented on src/main/java/ru/rtf/telegramBot/learning/LearningSession.java
> +        return allCards.peek().toString();
1. Заменили `toString()` на `getDescription()`
2. Добавлена обработка NPE в метод `getActiveCard`
3. Изменили метод `String getActiveCardDescription()` на `Card getActiveCard()`

2024-12-09 11:47 UTC, merged