Task1 almazova
k4noise/AnkiBot pull request #2
Opened 2024-10-28 11:05 UTC by VladaAlmazova

добавила логику работы с картами 
![image](https://github.com/user-attachments/assets/a6a09457-15ae-4ca3-b4f6-0f6bb1827f41)
![image](https://github.com/user-attachments/assets/c3171666-c910-4a4f-b02b-73b6003acfed)

Добавила телеграм бота (токен вводится в переменную окружения)

пока связь пользователей с колодами работает через класс UserDecksData
![image](https://github.com/user-attachments/assets/f9b1768b-8389-4ff2-a3d4-ccbbc6c62683)

Все команды хранятся в классе CommandManager
![image](https://github.com/user-attachments/assets/7238b072-2b04-4ad0-b2e5-2acb691993f4)

Пока добавлены только команды для работы с колодами (без карточек)
![image](https://github.com/user-attachments/assets/3859cc2c-ce97-4dc4-af84-1de6c24a31e3)
![image](https://github.com/user-attachments/assets/0aeb9603-4a0f-428a-ad6d-759dca409089)
![image](https://github.com/user-attachments/assets/7a28276c-c32c-402f-af82-a3c0e1010f24)
![image](https://github.com/user-attachments/assets/27f491ab-45f8-4462-8211-3b39b1901703)

Для тестирования работы бота добавила mockito-core в зависимости. 
Пока не исправляла конфликты и уязвимости зависимостей

2024-10-28 12:24 UTC, k4noise requested changes

2024-10-28 12:24 UTC, k4noise commented on pom.xml
> +            <version>5.11.0</version>
Версию стоит вынести в `property`

2024-10-28 12:24 UTC, k4noise commented on pom.xml
> +            <version>5.11.0</version>
Тут тоже версию стоит вынести в `property`

2024-10-28 12:24 UTC, k4noise commented on src/main/java/ru/rtf/telegramBot/Commands/DeleteDeckCommand.java
> +        if (message.split(" ").length < 2) {
Не сразу очевидно, почему 2. Позже поняла, что ты считала аргументы команды.
Возможно, лучше вынести в константу.
Для всех остальных команд тоже стоит подумать над этим.

2024-10-28 12:24 UTC, k4noise commented on src/test/java/ru/rtf/CardTest.java
> +    @Test
Куда-то пропал JavaDoc

2024-10-28 12:24 UTC, k4noise commented on src/test/java/ru/rtf/CardTest.java
> +    @Test
И тут пропал JavaDoc

2024-10-28 12:24 UTC, k4noise commented on src/test/java/ru/rtf/telegramBot/CommandManagerTest.java
> +class CommandManagerTest {
JavaDoc на класс пропал

И аж целых 2 `static`))

2024-10-28 12:24 UTC, k4noise commented on src/test/java/ru/rtf/telegramBot/Commands/CreateDeckCommandTest.java
> +import static org.mockito.Mockito.*;
Можем получить за `static`

2024-10-28 12:24 UTC, k4noise commented on src/test/java/ru/rtf/telegramBot/Commands/DeleteDeckCommandTest.java
> +import static org.mockito.Mockito.*;
Можем получить за `static`

2024-10-28 12:24 UTC, k4noise commented on src/test/java/ru/rtf/telegramBot/Commands/DeleteDeckCommandTest.java
> +class DeleteDeckCommandTest {
Потерялся JavaDoc у класса

2024-10-28 12:24 UTC, k4noise commented on src/test/java/ru/rtf/telegramBot/Commands/ListDecksCommandTest.java
> +import static org.mockito.Mockito.*;
Можем получить за `static`

2024-10-28 12:24 UTC, k4noise commented on src/test/java/ru/rtf/telegramBot/Commands/ListDecksCommandTest.java
> +public class ListDecksCommandTest {
Потерялся JavaDoc у класса

2024-10-28 12:24 UTC, k4noise commented on src/test/java/ru/rtf/telegramBot/Commands/RenameDeckCommandTest.java
> +import static org.mockito.Mockito.*;
Можем получить за `static`

2024-10-28 12:24 UTC, k4noise commented on src/test/java/ru/rtf/telegramBot/Commands/RenameDeckCommandTest.java
> +class RenameDeckCommandTest {
Потерялся JavaDoc у класса

2024-10-28 12:24 UTC, k4noise commented on src/test/java/ru/rtf/telegramBot/UserDeckDataTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Можем получить за `static`

2024-10-28 12:24 UTC, k4noise commented on src/test/java/ru/rtf/telegramBot/UserDeckDataTest.java
> +class UserDecksDataTest {
Потерялся JavaDoc у класса

2024-10-28 13:19 UTC, VladaAlmazova commented on pom.xml
> +            <version>5.11.0</version>
сделано

2024-10-28 13:19 UTC, VladaAlmazova commented on pom.xml
> +            <version>5.11.0</version>
сделано

2024-10-28 13:20 UTC, VladaAlmazova commented on src/main/java/ru/rtf/telegramBot/Commands/DeleteDeckCommand.java
> +        if (message.split(" ").length < 2) {
вынесла

2024-10-28 13:22 UTC, VladaAlmazova commented on src/main/java/ru/rtf/telegramBot/Commands/DeleteDeckCommand.java
> +        if (message.split(" ").length < 2) {
не стала добавлять вычисление индекса из константы, мне показалось это бы ухудшило читаемость

2024-10-29 19:16 UTC, VladaAlmazova commented
Изменила структуру классов команд. 
Вынесла в отдельный класс функционал по обработке сообщений от пользователя.
Перенесла загрузку команд в класс бота. 
В менеджер команд добавила автоматическое добавление новому пользователю экземпляра класса для управления колодами.  И добавила проверку на количество параметров

2024-10-30 05:13 UTC, k4noise approved these changes
Ок

2024-10-30 05:13 UTC, merged