исправление
k4noise/AnkiBot pull request #22
Opened 2024-11-28 18:45 UTC by VladaAlmazova

1. Сделала вместо интерфейса абстрактный класс (не уверена какую видимость поставить строковым константам)
2. исправила последствия своей невнимательности (лишние слеши)
3. объединила тесты в командах обучения
4. вынесла random в отдельное поле
5. assertTrue и assertFalse заменены на assertEquals
6. удалила метод get из sessionManager

2024-11-29 11:06 UTC, k4noise requested changes

2024-11-29 11:06 UTC, k4noise commented on src/main/java/ru/rtf/telegramBot/learning/LearningSession.java
> +    protected static String SHOW_RIGHT_ANSWER = """
тут private, можешь докинуть final

2024-11-29 11:06 UTC, k4noise commented on src/main/java/ru/rtf/telegramBot/learning/LearningSession.java
> +    protected static final String CORRECT_ANSWER_INFO = "Верно! " + SHOW_RIGHT_ANSWER;
тут мб уместнее public, смысла в ограничении не вижу
для следующей константы то же самое

2024-11-29 11:06 UTC, k4noise commented on src/main/java/ru/rtf/telegramBot/learning/LearningSession.java
> +    public Card pollActiveCard() {
> снова тёмная сторона. И удаляет и что-то возвращает

оригинал замечания, и по мне, ничего особо не изменилось. Как вариант можно сделать 2 метода - `getActiveCardDescription`, который просто вернет описание без удаления и `completeActiveCardStudy`, который и удалит карту из списка изучаемых. На единственное правильное решение не претендую, мб придумаешь лучше

2024-11-29 11:06 UTC, k4noise commented on src/main/java/ru/rtf/telegramBot/learning/SessionManager.java
> +        String activeCardDescription = (learningSession.pollActiveCard()).toString();
скобки тут не нужны

2024-11-29 11:06 UTC, k4noise commented on src/test/java/ru/rtf/telegramBot/commands/EndCheckCommandHandlerTest.java
> +class EndCheckCommandHandlerTest {
крутой тест! и статический импорт
`LearnCheckCommandHandlerTest` аналогично

2024-11-29 11:06 UTC, k4noise commented on src/test/java/ru/rtf/telegramBot/commands/EndCheckCommandHandlerTest.java
> +class EndCheckCommandHandlerTest {
если ты не планируешь(планировала) писать тесты на них сама, то лучше удали, иначе забудем

2024-11-29 11:06 UTC, k4noise commented on src/test/java/ru/rtf/telegramBot/learning/SessionManagerTest.java
> -        Assertions.assertTrue(sessionManager.hasActive(chatId), "Должна быть создана активная сессия");
я не думаю, что замечание относилось к `assertTrue`, а вот в методе ниже был `contains`, а вот это уже и есть ненадежная проверка.
![image](https://github.com/user-attachments/assets/e337f387-7442-4731-a945-1f5376e5cd37)
на этот метод я бы правки не вносила бы, а уточнила, точно ли к этой строчке замечание, так как там и был assertEquals без доп условий.
Правка - на твое усмотрение, ошибкой как бы не является (именно это преобразование)

2024-11-29 11:06 UTC, k4noise commented on src/test/java/ru/rtf/telegramBot/learning/SessionManagerTest.java
> +        Assertions.assertEquals(true, endMessage.contains("Вы прошли все карточки в колоде!"));
вот тут `contains` - и есть ненадежная проверка

2024-12-01 12:50 UTC, VladaAlmazova commented on src/test/java/ru/rtf/telegramBot/learning/SessionManagerTest.java
> +        Assertions.assertEquals(true, endMessage.contains("Вы прошли все карточки в колоде!"));
написала полный текст сообщения

2024-12-01 12:52 UTC, VladaAlmazova commented on src/test/java/ru/rtf/telegramBot/learning/SessionManagerTest.java
> -        Assertions.assertTrue(sessionManager.hasActive(chatId), "Должна быть создана активная сессия");
я думаю, пока оставить везде assertEquals, думаю это немного улучшает читаемость

2024-12-01 12:52 UTC, VladaAlmazova commented on src/test/java/ru/rtf/telegramBot/commands/EndCheckCommandHandlerTest.java
> +class EndCheckCommandHandlerTest {
убрала

2024-12-01 12:52 UTC, VladaAlmazova commented on src/test/java/ru/rtf/telegramBot/commands/EndCheckCommandHandlerTest.java
> +class EndCheckCommandHandlerTest {
и файл для тестов на команду обучения

2024-12-01 12:53 UTC, VladaAlmazova commented on src/main/java/ru/rtf/telegramBot/learning/SessionManager.java
> +        String activeCardDescription = (learningSession.pollActiveCard()).toString();
ок

2024-12-01 12:53 UTC, VladaAlmazova commented on src/main/java/ru/rtf/telegramBot/learning/LearningSession.java
> +    public Card pollActiveCard() {
разделила методы

2024-12-01 12:53 UTC, VladaAlmazova commented on src/main/java/ru/rtf/telegramBot/learning/LearningSession.java
> +    protected static final String CORRECT_ANSWER_INFO = "Верно! " + SHOW_RIGHT_ANSWER;
ок

2024-12-01 12:54 UTC, VladaAlmazova commented on src/main/java/ru/rtf/telegramBot/learning/LearningSession.java
> +    protected static String SHOW_RIGHT_ANSWER = """
добавила

2024-12-01 15:41 UTC, k4noise commented on src/test/java/ru/rtf/telegramBot/learning/SessionManagerTest.java
> -        Assertions.assertTrue(sessionManager.hasActive(chatId), "Должна быть создана активная сессия");
касаемо читаемости спорно, но ок, пусть будет так

2024-12-01 15:46 UTC, k4noise commented on src/main/java/ru/rtf/telegramBot/learning/LearningSession.java
> +    protected static String SHOW_RIGHT_ANSWER = """
private не увидела, final увидела, могу потом докинуть сама
все же он у нас по замечаниям был...

2024-12-01 15:49 UTC, k4noise approved these changes
Если не учитывать `private`, то все исправлено. Правку показывать не надо.
Можешь мерджить

2024-12-01 15:56 UTC, merged