Task2 almazova
k4noise/AnkiBot pull request #24
Opened 2024-12-06 07:12 UTC by VladaAlmazova

![image](https://github.com/user-attachments/assets/c0033c3b-66eb-43e6-943e-46d9310b067b)

исправила замечания по поводу строковых констант, решила их вовсе убрать.
изменила везде toString на getDescription
метод getActiveCardDescription изменила на getActiveCard с исключением (тест на такое поведение придумать не удалось)

2024-12-06 10:01 UTC, k4noise requested changes
Касаемо теста: тут можно вполне удачно объединить `removeActiveCardFromStudy` и `getActiveCard` так: сначала получаешь активную карту, сравниваешь ее с ожидаемой (думаю, по описанию), далее удаляешь из списка к изучению и опять запрашиваешь активную карту, ловишь exception и проверяешь

2024-12-06 10:01 UTC, k4noise commented on src/main/java/ru/rtf/telegramBot/learning/LearningSession.java
> +    public Card getActiveCard() {
NPE обработан только в этом методе, но он может быть не только тут, правда? 
Подсказка: есть 3 класса, расширяющих этот абстрактный класс и для всех этих классов доступен этот метод, а также есть волшебное выделение желтой линией.
PS: а потом это еще надо и в JavaDoc отразить

Пример из `MatchLearning`:
![image](https://github.com/user-attachments/assets/2d322b41-8eae-4830-91ee-744b466dcecc)

2024-12-06 10:01 UTC, k4noise commented on src/main/java/ru/rtf/telegramBot/MessageHandler.java
> +        try {
и без try-catch нормально работает, поскольку мы обрабатываем явно ситуацию, когда карт не осталось

2024-12-06 10:01 UTC, k4noise commented on src/main/java/ru/rtf/telegramBot/MessageHandler.java
>          if (!learningSession.hasCardsToLearn()) {
вот тут обрабатываем, поэтому exception просто не выбросится, так как мы раньше завершим обучение, чем сделаем запрос к пустой колоде для изучения

2024-12-09 10:08 UTC, VladaAlmazova commented on src/main/java/ru/rtf/telegramBot/learning/LearningSession.java
> +    public Card getActiveCard() {
теперь в классах-наследниках вместо `allCards.peek()` используется `getActiveCard()`

2024-12-09 10:09 UTC, VladaAlmazova commented on src/main/java/ru/rtf/telegramBot/MessageHandler.java
> +        try {
убрала

2024-12-09 10:10 UTC, VladaAlmazova commented
добавила тест, но сравнение сделала по термину. Так же не стала дублировать тест во все классы-наследники, так как он проверяет только методы абстрактного класса.

2024-12-09 11:21 UTC, k4noise approved these changes
по замечаниям - ок

2024-12-09 11:26 UTC, merged