Выполнена задача 1
k4noise/AnkiBot pull request #7
Opened 2024-10-30 17:34 UTC by VladaAlmazova

Добавление базовой архитектуры.
Базовые функции для работы с колодами и картами.
Создан телеграм бот.

2024-10-31 16:19 UTC, YaEtoTui commented
1) Вау, отличное портфолио, архитектура продумана, ООП на высшем уровне.
Критерии выполнены.

2) Работа проделана качественно, спасибо вам за вашу работу)

3) Есть тут мои комментарии, они ремарка, вам на подумать

4) По поводу принимания строк, не задумывались принимать строки, не считая регистр?

5) В будущем, когда будете писать режимы. Думаю стоит, чтобы не каждый раз проходить в тг боте -> создать 
либо файл с данными, либо захардкодить (в коде прописать). Про бд не буду писать, и так много делать вам)
Я бы подумал, чтобы вы еще подумали над логированием (чтобы смотреть какой балл имеет), упростит проверку логики. Хотя может это тестами получится сделать. Вот вам оставил идей на подумать

2024-10-31 16:19 UTC, YaEtoTui commented
1 задание принято

2024-11-10 16:43 UTC, vpyzhyanov requested changes
Принимаю вас в адепты тёмной стороны) Может лучше на светлую? Там легче, проще и понятнее

2024-11-10 16:43 UTC, vpyzhyanov commented on pom.xml
> +        <telegrambot.version>6.9.7.1</telegrambot.version>
лучше называть свойства в соответствие с рекомендацией от Maven: `artifactId.version`

2024-11-10 16:43 UTC, vpyzhyanov commented on pom.xml
> +            <artifactId>telegrambots</artifactId>
у этой библиотеки есть уязвимость. И вы даже знаете как её решать

2024-11-10 16:43 UTC, vpyzhyanov commented on src/test/java/ru/rtf/CardTest.java
> +                IllegalArgumentException.class, () -> new Card("", ""), "Карта с пустыми параметрами не может быть создана"
на последнем занятии я рассказывал как тестируются исключения. Надо исправить

2024-11-10 16:43 UTC, vpyzhyanov commented on src/test/java/ru/rtf/CardTest.java
> +                IllegalArgumentException.class, () -> new Card("", "abс"), "Карта с пустым термином не может быть создана"
прошу не увлекаться однострочным программированием. Это не удобно. Один перенос строки кардинально улучшает ситуацию

2024-11-10 16:43 UTC, vpyzhyanov commented on src/test/java/ru/rtf/CardTest.java
> +        String actualTerm = card.getTerm();
Не занимайтесь бюрократией, пожалуйста. Элементарные геттеры не надо тестировать. Тестируйте лучше логику.

2024-11-10 16:43 UTC, vpyzhyanov commented on src/test/java/ru/rtf/CardTest.java
> +        String actualDefinition = card.getDefinition();
Не занимайтесь бюрократией, пожалуйста. Элементарные геттеры не надо тестировать. Тестируйте лучше логику.

2024-11-10 16:43 UTC, vpyzhyanov commented on src/test/java/ru/rtf/CardTest.java
> +    void testHashCode() {
такие мелочи тоже можно не тестировать.

2024-11-10 16:43 UTC, vpyzhyanov commented on src/test/java/ru/rtf/DeckTest.java
> + * @author k4noise
кто это? Пишите понятные имена

2024-11-10 16:43 UTC, vpyzhyanov commented on src/test/java/ru/rtf/DeckTest.java
> +class DeckTest {
много тривиальных тестов (вроде тестирования геттеров , equals, hashcode), которых существовать не должно.

2024-11-10 16:43 UTC, vpyzhyanov commented on src/test/java/ru/rtf/telegramBot/UserDeckDataTest.java
> +class UserDecksDataTest {
имя файла не совпадает с именем класса

2024-11-10 16:43 UTC, vpyzhyanov commented on src/test/java/ru/rtf/telegramBot/MessageProcessorTest.java
> +class MessageProcessorTest {
Добро пожаловать на тёмную сторону. Вам успешно удалось запутать всех. Тесты на обработку сообщений не проверяют обработку сообщений, а всё потому, что MessageProcessor не занимается обработкой сообщений.

**Обработка** - это не **парсинг** команды.  В результате обработки появляется **ответ** на сообщение пользователя.

У вас он должен называться `CommandParser`

2024-11-10 16:43 UTC, vpyzhyanov commented on src/test/java/ru/rtf/telegramBot/CommandHandlerManagerTest.java
> +    private final Map<String, CommandHandler> commands = new LinkedHashMap<>();
1. Почему выбрали именно такую коллекцию
2. Хм... подохрительно видеть такое поле в **тесте**... похоже тут надо искать дублирование реализации

2024-11-10 16:43 UTC, vpyzhyanov commented on src/test/java/ru/rtf/telegramBot/CommandHandlerManagerTest.java
> +    private void uploadCommands() {
1. Под словом upload все понимают загрузку данных на сервер. У вас этого нет, поэтому вам лучше использовать намного более близкое по смыслу слово `initialize`
2. Вот вы и попались. Нашёл дублирование. Притом идентичную копию. А теперь дружно это всё выкидываем отсюда и больше никогда не дублируем реалзиацию в тестах!

![image](https://github.com/user-attachments/assets/489042ab-44fc-4a53-8767-f9344ec34792)

2024-11-10 16:43 UTC, vpyzhyanov commented on src/test/java/ru/rtf/telegramBot/CommandHandlerManagerTest.java
> +    private void uploadCommands() {
Самое забавное, что у вас вообще нет никакой необходимости что-то дублировать. Я не могу понять зачем вы это сделали

2024-11-10 16:43 UTC, vpyzhyanov commented on src/test/java/ru/rtf/telegramBot/CommandHandlerManagerTest.java
> +class CommandHandlerManagerTest {
Похоже у вас бесконечно много свободного времени, поэтому вы пишете тесты, которые дублируют друг друга и делают одни и те же проверки. Либо вы очень сильно увязли в тёмной стороне и внедрили коллективную безответственность в тесты (обычно так никто не делает).

Конкретно этот тест проверяет работу команд и весь пакет `ru.rtf.telegramBot.Commands` проверяет работу команд. Они делают **одно и то же**. Если вы собираетесь делать это в CommandHandlerManagerTest, то весь пакет `ru.rtf.telegramBot.Commands` можно смело удалять вместе со всеми тестами.

Либо есть другой вариант: на самом деле тестировать именно CommandHandlerManager, а в пакете реально тестировать команды `ru.rtf.telegramBot.Commands`. Чтобы понять как тестировать CommandHandlerManager нужно более детально расписать его предназначение (подсказка: с выполнением команд он вообще не связан).

2024-11-10 16:43 UTC, vpyzhyanov commented on src/test/java/ru/rtf/telegramBot/Commands/RenameDeckCommandHandlerTest.java
> +    private UserDecksData userDecksData;
интересный факт: это поле в тесте вообще не принимает участие. Оно вызывается, но смысла в этих вызовах нет. Прошу его удалить. И из всех других тестов на команды тоже.

2024-11-10 16:43 UTC, vpyzhyanov commented on src/main/java/ru/rtf/Main.java
> +        String telegramBotName = "AnkiSimpleBot";
имя бота тоже лучше вынести в параметр. Имя тесно связано с токеном. И оно может поменяться.

2024-11-10 16:43 UTC, vpyzhyanov commented on src/main/java/ru/rtf/Main.java
>  public class Main {
не вижу JavaDoc!

2024-11-10 16:43 UTC, vpyzhyanov commented on src/main/java/ru/rtf/telegramBot/TelegramBotCore.java
> +    private final UserDecksData userDecksData;
1. Поле нигде не используется как поле. Не надо сохранять что-то в состояние класса, чем вы пользоваться не собираетесь
2. Добро пожаловать на тёмную сторону. Единственный класс, кому нужен этот объект это CommandHandlerManager, дак почему ответственность за его создание лежит на TelegramBotCore? Пусть сам себе создаст поле, которое ему нужно.

2024-11-10 16:43 UTC, vpyzhyanov commented on src/main/java/ru/rtf/telegramBot/TelegramBotCore.java
> +    private final Map<String, CommandHandler> commands = new LinkedHashMap<>();
и снова тёмная сторона. Точно ли телеграмм бот должен заботиться о том, какие команды он будет выполнять? Нет, ему не важно какие у вас команды, его задача только принимать и отправлять сообщения. Команды нужны только обработчику сообщений и больше никому

2024-11-10 16:43 UTC, vpyzhyanov commented on src/main/java/ru/rtf/telegramBot/TelegramBotCore.java
> +    private final Map<String, CommandHandler> commands = new LinkedHashMap<>();
почему вы выбрали именно такую коллекцию?

2024-11-10 16:43 UTC, vpyzhyanov commented on src/main/java/ru/rtf/telegramBot/TelegramBotCore.java
> +        uploadCommands();
а если бы метод назвали в соответствие с тем, что он делает, то такие уточняющие комментарии бы не понадобились

Про то, что такого метода тут быть вообще не должно я уже писал

2024-11-10 16:43 UTC, vpyzhyanov commented on src/main/java/ru/rtf/telegramBot/CommandHandlerManager.java
> +public class CommandHandlerManager {
1. Название перегружено словами, звучит как "УправленецОбработчикКоманд". Одно слово явно лишнее.
2. Надо уточнить что означает "управление", это вам пригодится для тестирование

2024-11-10 16:43 UTC, vpyzhyanov commented on src/main/java/ru/rtf/telegramBot/CommandHandlerManager.java
> +     * Хранилище колод пользователя по id чата
внутренние детали тут не надо писать

2024-11-10 16:43 UTC, vpyzhyanov commented on src/main/java/ru/rtf/telegramBot/CommandHandlerManager.java
> +    public CommandHandler getByName(String nameCommand) {
Инкапсуляция вышла погулять и не вернулась. Метод должен быть private и никаким другим, т.к. он обращается к внутренней структуре, о которой никому другому знать вообще не обязательно.

2024-11-10 16:43 UTC, vpyzhyanov commented on src/main/java/ru/rtf/telegramBot/CommandHandlerManager.java
> +        MessageProcessor partsMessage = new MessageProcessor(text);
мы уже в тестах заметили, что тут вы вводите в заблуждение. Перепутали понятие "парсинг" с "обработка"

2024-11-10 16:43 UTC, vpyzhyanov commented on src/main/java/ru/rtf/telegramBot/CommandHandlerManager.java
> +    public String execute(Long chatId, String text) {
К двум словам названия метода добавилось ещё и третье "Executor". Слишком много понятий намешано. Нужно навести порядок и использовать одно. Если Handler, то `handle`, если Executor, то `exectute`.

То есть создавая класс нужно понимать, что его методы должны соответствовать ему. Иначе будет "кто в лес кто по дрова"

2024-11-10 16:43 UTC, vpyzhyanov commented on src/main/java/ru/rtf/telegramBot/CommandHandlerManager.java
> +            return e.getMessage();
1. "Вовка в тридевятом царстве. Возвращение"))) Сами в этом же классе создали исключение, сами его обработали. Зато кучу лишнего кода написали. Если что баллы ставятся на за количество строк кода, а за их качество. И как правило, чем меньше строк кода, тем выше качество.
2. Должно быть человекочитаемое сообщение об ошибке, а не просто текст исключения

P.S. 2 строчки кода, которые используются в одном единственном месте не стоят выноса в отдельный метод. А на самом деле там вообще одна строчка должна быть.

2024-11-10 16:43 UTC, vpyzhyanov commented on src/main/java/ru/rtf/telegramBot/CommandHandlerManager.java
> +        if (commands.containsKey(nameCommand))
лишняя операция. Одного get достаточно

2024-11-10 16:43 UTC, vpyzhyanov commented on src/main/java/ru/rtf/telegramBot/CommandHandlerManager.java
> +            return commandHandler.execute(userDecksData.getUserDecks(chatId), paramsCommand);
никогда бы не подумал, что getUserDecks возвращает какой-то `DeckManager`. Если метод должен возвращать колоды, то пусть их и возвращает! `Collection<Deck>`

Интересный факт, что если написать словами то, чем занимается `DeckManager`, то получится название `UserDecksData`. Чем сейчас занимается существующие `UserDecksData` - непонятно. Ведь JavaDoc вводит нас в заблуждение, он пишет `Хранилище колод пользователей`, но это не так, в нём нет ни одной колоды.

Я бы предложил вообще удалить существующий класс `UserDecksData`, т.к. непонятно зачем он нужен. Как будь-то эту роль должен выполнять `CommandHandlerManager` и это его сфера ответственности

2024-11-10 16:43 UTC, vpyzhyanov commented on src/main/java/ru/rtf/telegramBot/CommandHandler.java
> +    String MessageComandError = """
Вообще-то это статическое поле и оно должно называться соответствующе `MESSAGE_COMMAND_ERROR.` И желательно с соблюдением грамматики, пропущена буква.

2024-11-10 16:43 UTC, vpyzhyanov commented on src/main/java/ru/rtf/telegramBot/Commands/CreateCardCommandHandler.java
> +package ru.rtf.telegramBot.Commands;
пакеты надо называть с маленькой буквы

2024-11-10 16:43 UTC, vpyzhyanov commented on src/main/java/ru/rtf/telegramBot/Commands/CreateCardCommandHandler.java
> +    private final int COUNT_PARAMS = 3;
static

2024-11-10 16:43 UTC, vpyzhyanov commented on src/main/java/ru/rtf/telegramBot/Commands/CreateDeckCommandHandler.java
> +    private final int COUNT_PARAMS = 1;
static. И так во всех командах

2024-11-10 16:43 UTC, vpyzhyanov commented on src/main/java/ru/rtf/DeckManager.java
> +        decks = new LinkedHashMap<>();
почему коллекция именно такая?

2024-11-10 16:43 UTC, vpyzhyanov commented on src/main/java/ru/rtf/DeckManager.java
> +        decks.put(name.toLowerCase(), new Deck(name));
мда... из предложения о регистронезависимости вы не должны были создавать себе кучу проблем. Создавая себе кучу проблем, вы буквально прыгаете на тёмную сторону. Притом никакого "выигрыша" от этого нет. Просто "бесплатно" решили себе усложнить задачу и добавить проблем. К сожалению пожертвовав ООП.

А теперь конкретно метод `.toLowerCase()` вызывается на каждый чих! В этом простом методе вызывается аж 2 раза. А в других вызывается по 3 и может даже более раз. При расширении это вызовет огромное количество проблем. Нет ничего проще, чем забыть его вызвать, особенно если его надо вызывать **почти** везде.

Лучше вызвать его **ОДИН** раз в самом начале, а дальше работать только с нижним регистром. Требование "писать пользователю сообщения в том же регистре, в котором он написал" - это вы сами придумали и это требование ничем не обосновано. Куча работы, а пользователь это вообще не оценит.

2024-11-10 16:43 UTC, vpyzhyanov commented on src/main/java/ru/rtf/Deck.java
> +        this.cards = new LinkedHashMap<>();
почему выбрали именно такую коллекцию?

2024-11-10 16:43 UTC, vpyzhyanov commented on src/main/java/ru/rtf/Deck.java
> +            throw new IllegalArgumentException("Имя колоды не может быть пустым");
дублирование

P.S. если вы заходите это вынести в метод, то это неправильный вариант, от него надо отказаться

2024-11-10 16:43 UTC, vpyzhyanov commented on src/main/java/ru/rtf/Deck.java
> +        return new Deck(newName, cards);
мне непонятно ваше решение создавать новую колоду. Вы оперируете **ИЗМЕНЯЕМЫМ** объектом, незачем тогда создавать новый.

Кстати, почему я утверждаю, что объект изменяемый?

2024-11-10 16:43 UTC, vpyzhyanov commented on src/main/java/ru/rtf/Deck.java
> +        return sb.toString();
добро пожаловать на тёмную сторону. Вы перегрузили класс функционалом. Его задача управлять карточками, формировать их текстовое представление для пользователя не входит в его задачу. Это ответственность команды.

2024-11-10 16:43 UTC, vpyzhyanov commented on src/main/java/ru/rtf/Deck.java
> +        cards.put(newTerm.toLowerCase(), oldCard.changeTerm(newTerm));
Добро пожаловать на тёмную сторону. Метод changeTerm вводит в заблуждение, он говорит о том, что меняет термин, но на самом деле он создаёт новую карточку. Догадаться до этого вообще невозможно.

На самом деле есть большой вопрос с смыслу существования метода changeTerm, ведь можно просто вызвать конструктор.

2024-11-10 16:43 UTC, vpyzhyanov commented on src/main/java/ru/rtf/Card.java
> +        return new Card(newTerm, definition);
то же самое, оперируя изменяемым объектом вы вдруг почему-то создаёте новый объект. Название об этом вообще не говорит.

2024-11-10 17:14 UTC, k4noise commented on src/main/java/ru/rtf/DeckManager.java
> +        decks = new LinkedHashMap<>();
`Linked` для сохранения порядка добавления колод. Используется для вывода колод пользователя в порядке добавления.
`HashMap` для операций поиска по имени колоды за константу.

2024-11-10 17:16 UTC, k4noise commented on src/main/java/ru/rtf/Deck.java
> +        this.cards = new LinkedHashMap<>();
`Linked` для сохранения порядка добавления карт. Используется для вывода карт пользователя в порядке их добавления.
`HashMap` для операций поиска по термину карты за константу.

2024-11-11 12:05 UTC, k4noise reviewed
Часть замечаний исправила:
https://github.com/k4noise/AnkiBot/pull/11

2024-11-11 12:05 UTC, k4noise commented on src/main/java/ru/rtf/telegramBot/CommandHandler.java
> +    String MessageComandError = """
Исправлено

2024-11-11 12:05 UTC, k4noise commented on src/main/java/ru/rtf/telegramBot/CommandHandlerManager.java
> +public class CommandHandlerManager {
1. Убрала `Handler`
2. Управляет передачей сообщения пользователя нужному обработчику команды, в JavaDoc дописала

2024-11-11 12:05 UTC, k4noise commented on src/main/java/ru/rtf/telegramBot/CommandHandlerManager.java
> +     * Хранилище колод пользователя по id чата
Детали убрала

2024-11-11 12:05 UTC, k4noise commented on src/main/java/ru/rtf/telegramBot/CommandHandlerManager.java
> +    public CommandHandler getByName(String nameCommand) {
Потребности в генерации исключения тут нет, с новой реализацией достаточно одного `.get()`.
Следовательно, метод удален

2024-11-11 12:05 UTC, k4noise commented on src/main/java/ru/rtf/telegramBot/CommandHandlerManager.java
> +        if (commands.containsKey(nameCommand))
Метод тоже лишний, был удален

2024-11-11 12:05 UTC, k4noise commented on src/main/java/ru/rtf/telegramBot/CommandHandlerManager.java
> +    public String execute(Long chatId, String text) {
Выбран `Handler`

2024-11-11 12:05 UTC, k4noise commented on src/main/java/ru/rtf/telegramBot/CommandHandlerManager.java
> +            return e.getMessage();
Когда вы рассказывали про эту ошибку после пары, я вообще думала про другой блок try-catch, но никак не этот. Тут есть и моя вина - я его пропустила на код ревью дважды...
Теперь у нас ошибка не генерируется и try-catch нам тут не нужен, реализация была переписана.

2024-11-11 12:05 UTC, k4noise commented on src/main/java/ru/rtf/telegramBot/CommandHandlerManager.java
> +            return commandHandler.execute(userDecksData.getUserDecks(chatId), paramsCommand);
`UserDecksData` удален, теперь менеджеры колод пользователей теперь хранятся в этом классе (Command~~Handler~~Manager)

2024-11-11 12:05 UTC, k4noise commented on src/main/java/ru/rtf/telegramBot/TelegramBotCore.java
> +    private final UserDecksData userDecksData;
1. `userDecksData` удален вместе с `commands`
2. Теперь Command~~Handler~~Manager сам себе создает такое хранилище

2024-11-11 12:05 UTC, k4noise commented on src/main/java/ru/rtf/telegramBot/TelegramBotCore.java
> +    private final Map<String, CommandHandler> commands = new LinkedHashMap<>();
Команды были пересены в Command~~Handler~~Manager

2024-11-11 12:05 UTC, k4noise commented on src/main/java/ru/rtf/telegramBot/TelegramBotCore.java
> +    private final Map<String, CommandHandler> commands = new LinkedHashMap<>();
Изначальный замысел подразумевал итерацию по командам для генерации справки, для этого выбрали `Linked`. `HashMap` для поиска и получения за константное время.
От этого замысла мы отказались и захардкодили справку, а `Linked` не убрали.

В Command~~Handler~~Manager это теперь просто `HashMap`.

2024-11-11 12:05 UTC, k4noise commented on src/main/java/ru/rtf/telegramBot/TelegramBotCore.java
> +        uploadCommands();
Метод удалили, текущая реализация подразумевает создание и добавление обработчиков команд прям в Command~~Handler~~Manager

2024-11-11 12:05 UTC, k4noise commented on src/test/java/ru/rtf/telegramBot/CommandHandlerManagerTest.java
> +    private final Map<String, CommandHandler> commands = new LinkedHashMap<>();
1. Ранее обосновывали тем, что хотели итерировать список команд для генерации справки
2. Поскольку Command~~Handler~~Manager теперь хранит обработчиков команд _сам_, то из теста удалили

2024-11-11 12:05 UTC, k4noise commented on src/test/java/ru/rtf/telegramBot/CommandHandlerManagerTest.java
> +class CommandHandlerManagerTest {
После вашего замечания про то, что стоит описать, как Command~~Handler~~Manager управляет командами (после изменения реализации), дополнился JavaDoc:
> Управляет передачей сообщения пользователя нужному обработчику команды

Раз управляет передачей, то теперь тестируется _передача_ сообщения пользователя нужному обработчику команды, а не проверка работы команд

2024-11-11 12:05 UTC, k4noise commented on src/test/java/ru/rtf/telegramBot/CommandHandlerManagerTest.java
> +    private void uploadCommands() {
1. Такого метода теперь нет, но теперь уяснили разницу между upload и initialize
2. Дружно выкинули, дублировалось из-за ошибки проектирования

2024-11-11 12:05 UTC, k4noise commented on src/test/java/ru/rtf/telegramBot/Commands/RenameDeckCommandHandlerTest.java
> +    private UserDecksData userDecksData;
Удалено из всех тестов на команды

2024-11-11 12:05 UTC, k4noise commented on src/test/java/ru/rtf/telegramBot/UserDeckDataTest.java
> +class UserDecksDataTest {
Класс теста удален

2024-11-11 12:05 UTC, k4noise commented on src/main/java/ru/rtf/telegramBot/Commands/CreateCardCommandHandler.java
> +package ru.rtf.telegramBot.Commands;
Исправлено

2024-11-11 12:05 UTC, k4noise commented on src/test/java/ru/rtf/telegramBot/MessageProcessorTest.java
> +class MessageProcessorTest {
Исправлено, разницу поняли

2024-11-11 12:05 UTC, k4noise commented on src/test/java/ru/rtf/telegramBot/MessageProcessorTest.java
> +class MessageProcessorTest {
JavaDoc на основной класс изменили:
> Парсер команд из сообщения пользователя

В тесте тоже:
> Тесты на парсера команд из сообщений пользователя

2024-11-11 12:05 UTC, k4noise commented on src/main/java/ru/rtf/telegramBot/CommandHandlerManager.java
> +        MessageProcessor partsMessage = new MessageProcessor(text);
Теперь это все же парсинг

2024-11-12 15:00 UTC, VladaAlmazova commented on pom.xml
> +        <telegrambot.version>6.9.7.1</telegrambot.version>
переименовала

2024-11-12 15:03 UTC, VladaAlmazova commented on pom.xml
> +            <artifactId>telegrambots</artifactId>
добавила dependencyManagementи, там исправила уязвимость

2024-11-12 15:03 UTC, VladaAlmazova commented on src/test/java/ru/rtf/CardTest.java
> +                IllegalArgumentException.class, () -> new Card("", ""), "Карта с пустыми параметрами не может быть создана"
добавила проверку сообщения исключения

2024-11-12 15:05 UTC, VladaAlmazova commented on src/test/java/ru/rtf/CardTest.java
> +                IllegalArgumentException.class, () -> new Card("", "abс"), "Карта с пустым термином не может быть создана"
добавила переносы

2024-11-12 15:06 UTC, VladaAlmazova commented on src/test/java/ru/rtf/CardTest.java
> +        String actualTerm = card.getTerm();
убрала лишние тесты

2024-11-12 15:06 UTC, VladaAlmazova commented on src/test/java/ru/rtf/CardTest.java
> +        String actualDefinition = card.getDefinition();
убрала лишние тесты

2024-11-12 15:07 UTC, VladaAlmazova commented on src/test/java/ru/rtf/CardTest.java
> +    void testHashCode() {
хорошо, убрала

2024-11-12 15:07 UTC, VladaAlmazova commented on src/test/java/ru/rtf/DeckTest.java
> +class DeckTest {
лишние тесты убрала

2024-11-12 15:08 UTC, VladaAlmazova commented on src/main/java/ru/rtf/Main.java
> +        String telegramBotName = "AnkiSimpleBot";
сделано, вынесла имя в параметры окружения

2024-11-12 15:08 UTC, VladaAlmazova commented on src/main/java/ru/rtf/Main.java
>  public class Main {
добавлен JavaDoc

2024-11-12 15:10 UTC, VladaAlmazova commented on src/main/java/ru/rtf/telegramBot/Commands/CreateCardCommandHandler.java
> +    private final int COUNT_PARAMS = 3;
добавлен static всем числовым константам в классах для обработки команд

2024-11-12 15:10 UTC, VladaAlmazova commented on src/main/java/ru/rtf/telegramBot/Commands/CreateDeckCommandHandler.java
> +    private final int COUNT_PARAMS = 1;
добавлен static всем числовым константам в классах для обработки команд

2024-11-12 15:11 UTC, VladaAlmazova commented on src/main/java/ru/rtf/Deck.java
> +            throw new IllegalArgumentException("Имя колоды не может быть пустым");
добавила вызов приватного конструктора из публичного, чтобы не дублировать код

2024-11-12 15:12 UTC, VladaAlmazova commented on src/main/java/ru/rtf/Deck.java
> +        return sb.toString();
перенесла этот метод в класс обработки команды для вывода карт колоды

2024-11-12 15:17 UTC, VladaAlmazova commented on src/main/java/ru/rtf/Deck.java
> +        cards.put(newTerm.toLowerCase(), oldCard.changeTerm(newTerm));
#большой вопрос с смыслу существования метода changeTerm
это было сделано с учетом того, что нам надо будет хранить баллы пользователя при изучении карточек. Чтобы они не потерялись мы решили добавить классу карты (и колоды) ответственность за перенос данных новому экземпляру

2024-11-13 12:51 UTC, k4noise commented on src/main/java/ru/rtf/Card.java
> +        return new Card(newTerm, definition);
теперь изменяем существующий

2024-11-13 12:53 UTC, k4noise commented on src/main/java/ru/rtf/Deck.java
> +        return new Deck(newName, cards);
Наше решение основано на том, что изменение имени у экземпляра колоды напрямую через сеттер минуя `DeckManager` нарушает согласованность имен колод в `DeckManager`. Возвращая измененную копию объекта, мы обеспечиваем согласованность имен колод в `DeckManager`

Переделала реализацию на прямые сеттеры с package-private доступом, тем самым мы ничего себе не ломаем.

>Кстати, почему я утверждаю, что объект изменяемый?

Потому что мы после создания можем изменить состояние объекта, так как имеем сеттеры на поля класса?

2024-11-13 12:54 UTC, k4noise commented on src/main/java/ru/rtf/DeckManager.java
> +        decks.put(name.toLowerCase(), new Deck(name));
реализация упрощена, `.toLowerCase()` вызывается только один раз в необходимых методах

2024-11-13 12:56 UTC, k4noise commented on src/main/java/ru/rtf/Deck.java
> +        cards.put(newTerm.toLowerCase(), oldCard.changeTerm(newTerm));
Теперь `changeTerm` изменяет термин экземпляра, а не создает новый.
С новой реализацией потребность в клонировании экземпляров отпала

2024-11-23 16:56 UTC, vpyzhyanov commented on src/test/java/ru/rtf/telegramBot/CommandHandlerManagerTest.java
> +class CommandHandlerManagerTest {
> Раз управляет передачей, то теперь тестируется _передача_ сообщения пользователя нужному обработчику команды, а не проверка работы команд

Это абсолютно правильно. Но у вас делается не так, почему-то. И я даже знаю почему)

Всё потому, что вы очень жёстко завязали список команд за CommandManager. Ключевое слово **жёстко**. Теперь вы не можете проверить передачу управления отдельно от проверки какой-то команды. Тут можно либо это просто принять и начать спокойно писать интеграционные тесты, либо пойти путём модульных тестов. Но для этого нужно немного изменить код следующим образом:

```java
    public CommandManager() {
        this(createDefaultCommandHandlers());
    }
 
    public CommandManager(List<CommandHandler> commandHandlers) {
        ....
    }
```

А в тесте используете полиморфизм и создаёте тестовый CommandHandler и передаёте его в конструктор. Дальше останется дело за малым. Проверить, что он вызвался когда должен был и не вызвался, когда не должен.

2024-11-23 17:14 UTC, vpyzhyanov commented on src/main/java/ru/rtf/Deck.java
> +        return new Deck(newName, cards);
Да, но не только сеттеры. Там много методов для изменения состояния.

То есть либо вы должны делать объект полностью неизменяемым (но в этой ситуации это неудачное решение) и тогда создавать копии, либо просто изменять объект. Миксовать одно с другим не надо.

2024-11-23 17:19 UTC, vpyzhyanov commented
Отлично. Образовательный процесс прошёл успешно. Задача принята, можете мёрджить

Оценка

- ООП - 5 баллов
- Git - 3 балла

2024-11-23 17:25 UTC, vpyzhyanov approved these changes
отлично

2024-11-23 17:27 UTC, merged